package com.rvcoding.mastermeme.ui.theme

import com.rvcoding.mastermeme.R

object Drawables {
    val memeMap = mapOf(
        R.drawable.bbctk_29 to "bbctk_29",
        R.drawable.ajtl_46 to "ajtl_46",
        R.drawable.boardroom_meeting_suggestion_36 to "boardroom_meeting_suggestion_36",
        R.drawable.byuiy_33 to "byuiy_33",
        R.drawable.c1hh_48 to "c1hh_48",
        R.drawable.c9dbh_30 to "c9dbh_30",
        R.drawable.change_my_mind_5 to "change_my_mind_5",
        R.drawable.clown_applying_makeup_31 to "clown_applying_makeup_31",
        R.drawable.disaster_girl_1 to "disaster_girl_1",
        R.drawable.eb198_32 to "eb198_32",
        R.drawable.epic_handshake_2 to "epic_handshake_2",
        R.drawable.eqjd8_12 to "eqjd8_12",
        R.drawable.eyvu_45 to "eyvu_45",
        R.drawable.f0mvv_16 to "f0mvv_16",
        R.drawable.grus_plan_9 to "grus_plan_9",
        R.drawable.hide_the_pain_harold_7 to "hide_the_pain_harold_7",
        R.drawable.i_bet_hes_thinking_about_other_women_10 to "i_bet_hes_thinking_about_other_women_10",
        R.drawable.i_was_told_there_would_be_35 to "i_was_told_there_would_be_35",
        R.drawable.iacv_13 to "iacv_13",
        R.drawable.igo27_47 to "igo27_47",
        R.drawable.is_this_a_pigeon_21 to "is_this_a_pigeon_21",
        R.drawable.jack_sparrow_being_chased_23 to "jack_sparrow_being_chased_23",
        R.drawable.jgrgn_44 to "jgrgn_44",
        R.drawable.left_exit_12_off_ramp_3 to "left_exit_12_off_ramp_3",
        R.drawable.leonardo_dicaprio_cheers_24 to "leonardo_dicaprio_cheers_24",
        R.drawable.op9wy_25 to "op9wy_25",
        R.drawable.otri4_40 to "otri4_40",
        R.drawable.p2is_38 to "p2is_38",
        R.drawable.qx7sw_49 to "qx7sw_49",
        R.drawable.rcrc1_39 to "rcrc1_39",
        R.drawable.reqtg_50 to "reqtg_50",
        R.drawable.running_away_balloon_14 to "running_away_balloon_14",
        R.drawable.sad_pablo_escobar_4 to "sad_pablo_escobar_4",
        R.drawable.scared_cat_34 to "scared_cat_34",
        R.drawable.soh_20 to "soh_20",
        R.drawable.su9f_41 to "su9f_41",
        R.drawable.sz4u_18 to "sz4u_18",
        R.drawable.t8r9a_26 to "t8r9a_26",
        R.drawable.the_rock_driving_8 to "the_rock_driving_8",
        R.drawable.third_world_skeptical_kid_11 to "third_world_skeptical_kid_11",
        R.drawable.two_buttons_6 to "two_buttons_6",
        R.drawable.two_buttons_28 to "two_buttons_28",
        R.drawable.u6ylb_19 to "u6ylb_19",
        R.drawable.vt4i_27 to "vt4i_27",
        R.drawable.w2e5e_17 to "w2e5e_17",
        R.drawable.waiting_skeleton_43 to "waiting_skeleton_43",
        R.drawable.wxtd1_42 to "wxtd1_42",
        R.drawable.yz6z4_22 to "yz6z4_22",
        R.drawable.zoa8_15 to "zoa8_15"
    )
}